### ISSUE TITLE
信息泄露

### ISSUE THREAD

**Issue by alswl** [cnfeat/Rime#1]
作为开智的学生 + Rime 用户，提醒你你的词库泄露了。

*   https://github.com/cnfeat/Rime/blob/master/sync/aef07baf-fc31-4dbf-911c-c1bc15ed306d/luna_pinyin.userdb.txt TXT 版本词库
*   https://github.com/cnfeat/Rime/tree/master/luna_pinyin.userdb LevelDB 存储的数据

删除文件的话，git 仍然会保留历史记录，建议整库删除。

**Comment by alswl** [comment]
例证：

嘉映 / 進化 / 錦強 / 榮捷 / 少娜

**Comment by cnfeat** [comment]
哈哈，现在才看到，感谢提醒，已经用上了。
