### ISSUE TITLE
请问一下为什么我在 default.custom.yaml文件里面打开了 comma 和 period 的翻页， 还是没有效果

### ISSUE THREAD

**Issue by woshichuanqilz** [cnfeat/Rime#3]
- {accept: bracketleft, send: Page_Up, when: paging}  
    - {accept: bracketright, send: Page_Down, when: has_menu}
    # - { when: has_menu, accept: semicolon, send: 2 }
    # - { when: has_menu, accept: apostrophe, send: 3 }
    - {accept: comma, send: Page_Up, when: paging}
    - {accept: period, send: Page_Down, when: has_menu}

**Comment by cnfeat** [comment]
这个我也不太清楚，建议去官方社区问一问。
